FROM node:18.12.0-alpine3.16
WORKDIR /app
COPY package.json .
RUN npm install
RUN npm cache clean –force
COPY . .
ENV REACT_APP_ANYVARNAME=REACT_APP_ANYVARNAME
ENV CHOKIDAR_USEPOLLING=true
RUN apk add mc
EXPOSE 3000
CMD ["npm", "start"]