# https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/

FROM node:16.17.0-bullseye-slim
RUN apt-get update \
	&& apt-get install -y --no-install-recommends dumb-init \
	&& apt-get clean
	
WORKDIR /app

COPY package.json .

# ! production
# RUN npm ci --only=production

# RUN rm -rf /app/node_modules/* \
# 	&& npm install \
# 	&& npm cache clean --force
RUN rm -rf /root/.cache/Cypress/*

COPY --chown=node:node . .

# ENV NODE_ENV production
ENV CHOKIDAR_USEPOLLING=true

# USER node

EXPOSE 3000

# ! production
# CMD ["dumb-init", "npm", "start"]

CMD ["npm", "start"]
